### ISSUE TITLE
Keep menu item even though there is no main window anymore

### ISSUE THREAD

**Issue by iSapozhnik** [XCOrganizer/IssuesTracker#18]
So right now whenever you close the main window, the app kills itself. I think it would be better if by clicking close button the user will just close the window but not the app itself thus keeping menu bar item available to reopen the window.

**Comment by Krivoblotsky** [comment]
@iSapozhnik 
Menu app is a standalone process bundled inside main app as LoginItem. You can use this option to keep menu app running.
<img width="748" alt="Screen Shot 2020-05-08 at 5 58 06 PM" src="https://user-images.githubusercontent.com/1411778/81418545-80f4dc80-9155-11ea-88be-bcfbaa6592e3.png">

**Comment by iSapozhnik** [comment]
Nice didn't know about this option :)
